### ISSUE TITLE
be consistent with the "buy arrow stacks"

### ISSUE THREAD

**Issue by slk333** [Zarant/Guidelime_Zarant#1]
I used your guide for leveling a night elf hunter from 1 to 22.
I encountered an issue not later than in the first few levels.

At one point you say (lvl 3 or 4): "buy 2 stack of arrows". We therefore assume you will tell us when to buy more arrows. Yet we find ourself running short of ammo later on because you didnt say on the next vendoring step to buy a stack or arrows. I suggest you do it consistently or remove it completely from the guide. Quite frustrating to run out of ammo in the middle of a quest or something like that.

**Comment by Zarant** [comment]
Fixed in version 4.2.1
