### ISSUE TITLE
be more explicit with the cooking quests requirement

### ISSUE THREAD

**Issue by slk333** [Zarant/Guidelime_Zarant#2]
For the darkshore segment, you said on stream that we need be level 10 in Cooking. Yet it's not indicated in the guide:

Currently in the guide:
[O] Make sure you have at least 9 small eggs to level cooking

Better:
[O] Make sure you have at least 9 small eggs to level cooking to 10

This mean we can skip it if we already levelled cooking with the eggs we got in teldrassil or else where

**Comment by Zarant** [comment]
Issue was properly addressed in version 4.2.1
